version: '3.8'
services:
  redis:
    image: redis:7.0-alpine
    restart: always
    ports: 
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
  ruby:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - .:/app
    command: ["tail", "-f", "/dev/null"]
volumes:
  redis:
    driver: local

